#!/bin/bash
d=100
c=1
for f in {1..6}
do
	for j in {1..5}
	do
		for v in {1..3}
		do
			for k in {1..3}
			do
				case "$k" in
				"1")
					d=100
				;;
				"2")
					d=500
				;;
				"3")
					d=1000
				;;
				esac
				echo c es: $c
				echo Funcion $f - Dimension $d - Vecindario $v
				./abejas ABC.cfg $f $d $v >>res/$parciales.txt
				c=$((c+1))
			done
		done
	done
done

