#!/bin/bash
d=100
c=1
for f in {1..6}
do
	for v in {1..3}
	do
		for k in {1..3}
		do
			case "$k" in
				"1")
				d=100
				;;
				"2")
				d=500
				;;
				"3")
				d=1000
				;;
			esac
			for c in {1..30}
			do
				echo Ejecuto: ABCF$fD$dV$v.cfg
				./abejas ./conf/abcF$fD$dV$v.cfg >> res/ultimas/C$cF$fD$dV$v.txt
			done
		done
	done
done
